---
######################### Clean up ##########################
- name: Post migration steps within the VM
  hosts: azure_windows
  gather_facts: false

  vars:
    # You can define the variable here, or let the task file use its default
    agent_name: "Azure Connected Machine Agent"

  tasks:
    - name: Run Azure Arc Uninstallation Tasks
      include_tasks: tasks/uninstall_arc_tasks.yml

    - name: Run VMware cleanup tasks
      ansible.builtin.include_tasks: tasks/disable_vmware_tasks.yml

    - name: Check hosts file having on-premises IP
      ansible.builtin.include_tasks: tasks/check_onprem_ip_in_hosts.yml
      #tasks/update_hosts_from_onprem.yml