---
####################   PowerOff and Rename On-Prem VMs   ##################
- name: Decommission (PowerOff and Rename) On-Prem VMs
  hosts: azure_windows
  gather_facts: false
  strategy: linear

  environment:
    PYTHONPATH: "{{ playbook_dir }}/lib:{{ lookup('env', 'PYTHONPATH') }}"

  vars:
    # Extracted from your original script
    vcenters_list:
      - 172.26.87.88   #  dfwvc01.levi.com
      - 172.26.87.208  #  dfwvcpg01.levi.com
      - 172.26.87.204  #  dfwvcno01.levi.com
      - 172.26.87.205  #  dfwvcnoe01.levi.com
      - 172.26.87.206  #  dfwvcneom01.levi.com
      - 172.26.87.1    #  dalvc20.levi.com
      - 172.26.87.92   #  dalvcpg20.levi.com
      - 172.26.87.93   #  dalvcpo20.levi.com
      - 172.26.87.94   #  dalvcpoe20.levi.com
      - 172.26.87.95   #  dalvcpeom20.levi.com

  tasks:
    - name: Decommission Execution Block
      throttle: 2
      block:
        - name: Include Decommission Logic
          ansible.builtin.include_tasks: tasks/poweroff_rename_vmware.yml

