---
#########################################################
####  Post Application Validation Steps for Windows VMs
#########################################################

- name: Delete Azure Arc Machines
  hosts: azure_linux
  connection: local
  gather_facts: false

  tasks:
    - name: Delete Azure Arc Machines
      throttle: 3
      block:
        - name: Include Deletion Logic
          ansible.builtin.include_tasks: tasks/delete_arc_vm.yml

    - name: Run Arc deletion Summary
      ansible.builtin.include_tasks: tasks/arc_summary.yml