---
####################   PowerOff and Rename On-Prem VMs   ##################
- name: Decommission (PowerOff and Rename) On-Prem VMs
  hosts: azure_windows
  gather_facts: false
  strategy: linear

  vars:
    script_path: "{{ playbook_dir }}/scripts/PowerOff-AndRenameVM.ps1"

  tasks:
    - name: Decommission Execution Block
      throttle: 2  # The script connects to 10 different vCenter in a loop for every single VM
      block:
        - name: Include Decommission Logic
          ansible.builtin.include_tasks: tasks/poweroff_rename_vmware.yml